services:
  backend:
    build:
      dockerfile: ./config/docker/Dockerfile.backend
      context: ./
    image: molyneux-backend:dev
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: ../config/docker/Dockerfile.frontend
      context: ./frontend
    image: molyneux-frontend:dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
