FROM python:3.10-slim

WORKDIR /app

COPY requirements.in requirements.in

ENV PYTHONUNBUFFERED=1

RUN pip install pip-tools
RUN pip-compile && pip-sync requirements.txt

COPY backend .

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
